[package]
name = "robot-rs-units"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.17.0"
approx = "0.5.1"
num-traits = "0.2.17"
