[package]
name = "wpilib-hal"
version = "0.1.0"
edition = "2021"

include = [
    "src/**/*",
    "Cargo.toml",
    "build.rs",
    "WPILIB_LICENSE",
    "lib/**/*",]

[package.metadata.robot_rs]
libs_dir = ["libs/"]

[dependencies]

[build-dependencies]
bindgen = "0.69.1"